use_frameworks!

platform :ios, '9.0'

target 'TestOne_Example' do
  pod 'TestOne', :path => '../'
  
#  pod 'RxSwift', '~> 4.2.0'

  target 'TestOne_Tests' do
    inherit! :search_paths

    
  end
end
